CREATE DATABASE EMPRESA;

CREATE TABLE PERSONA (
IDPERSONA INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
APELLIDO NVARCHAR (50) NOT NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDPERSONA),
);

CREATE TABLE EMPLEADO (
IDEMPLEADO INT IDENTITY (1,1) NOT NULL,
IDPERSONA INT,
PUESTO NVARCHAR (50) NOT NULL,
SALARIO MONEY NOT NULL,
FECHACONTRATACION DATE NOT NULL ,
PRIMARY KEY (IDEMPLEADO),
FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (IDPERSONA)
);
INSERT INTO PERSONA VALUES ( 'Jorge', 'Peralta', 'Activo');
INSERT INTO PERSONA VALUES ('Maria', 'Carranza', 'Activo');
INSERT INTO PERSONA VALUES ( 'Paola', 'Martinez', 'Inactivo');
INSERT INTO PERSONA VALUES ('Sebastian', 'Lopez', 'Activo');
INSERT INTO PERSONA VALUES ('Fernando', 'Condori', 'Activo');
 select* from PERSONA
 
INSERT INTO EMPLEADO VALUES (1, 'Gerente', 5000, '2023-06-12');
INSERT INTO EMPLEADO VALUES (2, 'Supervisor', 3500, '2023-06-22');
INSERT INTO EMPLEADO VALUES (3, 'Contador', 4500, '2023-07-23');
INSERT INTO EMPLEADO VALUES (4, 'Secretaria', 2500, '2023-07-29');
INSERT INTO EMPLEADO VALUES (5, 'Conserje', 3000, '2023-08-12');
select* from EMPLEADO   




   